### PR TITLE
Check Guide-Part1

### PR DESCRIPTION
**Pull request by Bala-Chen**
discord:拔辣
測試網址1:http://13.208.72.243:3000/api/attractions?page=4
測試網址2:http://13.208.72.243:3000/api/attractions?page=0&keyword=%E6%BA%AB%E6%B3%89
測試網址3:http://13.208.72.243:3000/api/attraction/12
測試網址4:http://13.208.72.243:3000/api/attraction/100

### CODE REVIEW

**Comment by cwpeng** [comment]
Response of http://13.208.72.243:3000/api/attractions?page=0&keyword=%E6%BA%AB%E6%B3%89 should return all first 12 attractions where title contains 溫泉。

We should search by keywords first and do pagination based on the filtered results.

ex. if there are only 2 results after searching, there is only 1 page. 
ex. if there are 15 results after searching, there are 2 pages.

fix it, create new commit and leave message for me to review again.

**Comment by Bala-Chen** [comment]
test url1:http://13.208.93.149:3000/api/attractions?page=4
test url2:http://13.208.93.149:3000/api/attractions?page=1&keyword=%E5%8C%97
test url3:http://13.208.93.149:3000/api/attraction/12
test url4:http://13.208.93.149:3000/api/attraction/100

**Comment by Bala-Chen** [comment]
discord name:拔辣
test url1:http://13.208.93.149:3000/api/attractions?page=4
test url2:http://13.208.93.149:3000/api/attractions?page=1&keyword=%E5%8C%97
test url3:http://13.208.93.149:3000/api/attraction/12
test url4:http://13.208.93.149:3000/api/attraction/100

**Review by cwpeng — APPROVED** [review]
OK. Good.

**Pull request merged**
